version: "3"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    networks:
      - postgres-compose-network

  web:
    build: .
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - pgadmin
    networks:
      - postgres-compose-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "teste@teste.com"
      PGADMIN_DEFAULT_PASSWORD: "pgpassword"
    ports:
      - "16543:80"
    depends_on:
      - db
    networks:
      - postgres-compose-network

  test:
    build: .
    command:
      ["./wait-for-it.sh", "db:5432", "--", "python", "manage.py", "test"]
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - postgres-compose-network

  coverage:
    build: .
    command:
      [
        "./wait-for-it.sh",
        "db:5432",
        "--",
        "coverage",
        "run",
        "manage.py",
        "test",
      ]
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - postgres-compose-network

networks:
  postgres-compose-network:
    driver: bridge
